version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
